# Generated by Django 4.2.8 on 2023-12-22 15:26

import json
import os

from django.conf import settings
from django.core.files import File
from django.db import migrations

from books.management.commands.get_books_from_tululu import JSON_PATH


def normalize_fullname(author: str) -> str:
    fullname_parts = author.strip().split()
    fullname_parts = [part.strip().capitalize() for part in fullname_parts]
    return ' '.join(fullname_parts)


def load_books(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    Genre = apps.get_model('books', 'Genre')
    Author = apps.get_model('books', 'Author')

    json_path = os.path.join(settings.BOOKS_DIR, JSON_PATH)
    with open(json_path, 'r') as file:
        books_json = json.load(file)
    for book in books_json:
        title = book.get('title')
        author_name = book.get('author')
        img_src = book.get('img_src')
        book_path = book.get('book_path')
        genre_names = book.get('genres')
        author_name = normalize_fullname(author_name)
        image_name = os.path.basename(img_src)
        text_name = os.path.basename(book_path)

        author = Author.objects.get_or_create(fullname=author_name)[0]
        genres = [Genre.objects.get_or_create(name=genre_name)[0] for genre_name in genre_names]

        with open(img_src, 'rb') as img_file, open(book_path, 'rb') as txt_file:
            book_obj = Book.objects.get_or_create(
                title=title,
                author=author,
                cover=File(img_file, image_name),
                text=File(txt_file, text_name)
            )[0]
            book_obj.genres.set(genres)


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_books)]
