name: Deploy

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build.yml
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOYUSER_SSH_PRIVATE_KEY }}

      - name: Disable Host key verification
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Copy docker-compose.yaml with tags
        run: scp ./deploy/docker-compose.yaml deployuser@books-library.ru:/etc/books-project
        
      - name: Pull image
        run: ssh deployuser@books-library "VERSION=${DOCKER_METADATA_OUTPUT_VERSION} docker compose pull"
        
      - name: Stop services
        run: ssh deployuser@books-library "VERSION=${DOCKER_METADATA_OUTPUT_VERSION} docker compose stop web nginx"
        
      - name: Run servises
        run: ssh deployuser@books-library "VERSION=${DOCKER_METADATA_OUTPUT_VERSION} docker compose up -d web nginx"
